<template>
    <div>
        <header>
            <HomeHeader/>
        </header>
        <main>
            <slot/>
        </main>
        <footer>
            <PageFooter/>
        </footer>
    </div>
</template>